import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Gold System App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white-200 h-screen grid place-content-center">
        <h1 className="heading1 font-bold">Gold System 101</h1>
      </main>
    </div>
  )
}
